---
- name: Install the MySQL packages
  apt: 
    name: "{{ item }}" 
    state: present  
    update_cache: yes
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb
    - libmysqlclient-dev
  become: yes

- name: Update MySQL root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: 
      - "{{ mysql_root_pass }}"
    state : present
  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost
    - '%'
  become: yes

- name: Copy the root credentials as .my.cnf file
  template: 
    src: root.cnf.j2 
    dest: ~/.my.cnf 
    mode: 0600
  become: yes

- name: Ensure Anonymous user(s) are not in the database
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  become: yes

- name: Remove the test database
  mysql_db: 
    name: test 
    state: absent
  notify:
    - Restart MySQL
  become: yes
