---
# tasks file for roles/blogsrvr
- name: Setting up Node base software
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - curl
    - checkinstall
    - libssl-dev
    - wget
    - npm
    - git
    - screen
    - acl
  become: yes

# Only for use with Vagrant
- name: Check if swap file exist
  stat:
    path: /var/swap.1
  register: swap_file_check

- name: Setting up swap space if not exist
  shell: "{{ item }}"
  with_items:
    - /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
    - /sbin/mkswap /var/swap.1
    - /sbin/swapon /var/swap.1
  become: yes
  when: not swap_file_check.stat.exists

#- name: Create Swap
#  shell: "{{ item }}"
#  with_items:
#    - /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
#    - /sbin/mkswap /var/swap.1
#    - /sbin/swapon /var/swap.1
#  become: yes

- name: Setting up Node & Express
  shell: "{{ item }}"
  with_items: 
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
    - bash -c '.  ~/.nvm/nvm.sh && nvm install v9.3.0'
    - bash -c '.  ~/.nvm/nvm.sh && nvm use --delete-prefix v9.3.0'
    - bash -c '.  ~/.nvm/nvm.sh && npm config set ca ""'
    - bash -c '.  ~/.nvm/nvm.sh && npm install -g nodemon'
    - bash -c '.  ~/.nvm/nvm.sh && npm install -g express --save'
    - bash -c '.  ~/.nvm/nvm.sh && npm config set unsafe-perm true'
  become: yes
  become_user: www-data

#- name: Remove Swap space
#  shell: "{{ item }}"
#  with_items:
#    - /sbin/swapoff /var/swap.1
#  become: yes

#- name: Node.js - Install bower and gulp globally
#  npm: name={{ item }} state=present global=yes
#  with_items:
#    - bower
#    - gulp
