aws_srvc_access_key = "YOUR_ACCESS_KEY_HERE" 
aws_srvc_secret_key = "YOUR_SECRET_KEY_HERE"
aws_srvc_key_path = "~/.ssh/private_key_to_use.pem"
aws_srvc_key_name = "private_key_name_to_use.pem"
aws_srvc_vpc_id = "vpc-id-where-is-your-subnet"
aws_srvc_subnet_id = "subnet-id-where-need-your-instance"
aws_srvc_kpair_public_key = "ssh-rsa-public-key-to-set-into-your-instance"
aws_srvc_ec2_type = "t2.micro-or-wherever-type-of-ec2-instance"
aws_srvc_ec2_volume_size = "disk-size-for-your-image-here-example(28)"
aws_srvc_availability_zone = "zone-where-you-need-this-instance-example(us-east-1e)"

